<script>
    var label_please_wait = "{{ get_label('please_wait', 'Please wait...') }}";
    var label_please_select_records_to_delete = "{{ get_label('please_select_records_to_delete', 'Please select records to delete.') }}";
    var label_something_went_wrong = "{{ get_label('something_went_wrong', 'Something went wrong.') }}";
    var label_please_correct_errors = "{{ get_label('please_correct_errors', 'Please correct errors.') }}";
    var label_removed_from_favorite_successfully = "{{ get_label('removed_from_favorite_successfully', 'Removed from favorites successfully.') }}";
    var label_marked_as_favorite_successfully = "{{ get_label('marked_as_favorite_successfully', 'Marked as favorite successfully.') }}";
    var label_yes = "{{ get_label('yes', 'Yes') }}";
    var label_upload = "{{ get_label('upload', 'Upload') }}";
    var decimal_points = {{ intval($general_settings['decimal_points_in_currency'] ?? '2') }};
    var label_update = "{{ get_label('update', 'Update') }}";
    var label_delete = "{{ get_label('delete', 'Delete') }}";
    var label_view = "{{ get_label('view', 'View') }}";
    var label_not_assigned = "{{ get_label('not_assigned', 'Not assigned') }}";
    var label_delete_selected = "{{ get_label('delete_selected', 'Delete selected') }}";
    var label_search = "{{ get_label('search', 'Search') }}";
    var label_create = "{{ get_label('create', 'Create') }}";
    var label_users_associated_with_project = "{{ get_label('users_associated_with_project', 'Users associated with project') }}";
    var label_update_task = "{{ get_label('update_task', 'Update Task') }}";
    var label_quick_view = "{{ get_label('quick_view', 'Quick View') }}";
    var label_project = "{{ get_label('project', 'Project') }}";
    var label_task = "{{ get_label('task', 'Task') }}";
    var label_projects = "{{ get_label('projects', 'Projects') }}";
    var label_tasks = "{{ get_label('tasks', 'Tasks') }}";
    var label_clear_filters = "{{ get_label('clear_filters', 'Clear Filters') }}";
    var label_set_as_default_view = "{{ get_label('set_as_default_view', 'Set as Default View') }}";
    var label_default_view = "{{ get_label('default_view', 'Default View') }}";
    var label_save_column_visibility = "{{ get_label('save_column_visibility', 'Save Column Visibility') }}";
    var label_showing = "{{ get_label('showing', 'Showing') }}";
    var label_to_for_pagination = "{{ get_label('to_for_pagination', 'to') }}";
    var label_of = "{{ get_label('of', 'of') }}";
    var label_rows = "{{ get_label('rows', 'rows') }}";
    var label_rows_per_page = "{{ get_label('rows_per_page', 'rows per page') }}";
    var label_select = "{{ get_label('select', 'Select') }}";
    var label_or = "{{ get_label('or', 'or') }}";
    var label_drag_and_drop_files_here = "{{ get_label('drag_and_drop_files_here', 'Drag & Drop Files Here') }}";
    var label_drag_and_drop_update_zip_file_here = "{{ get_label('drag_and_drop_update_zip_file_here', 'Drag & Drop Update from vX.X.X to vX.X.X.zip file Here') }}";
    var label_only_one_file_can_be_uploaded_at_a_time = "{{ get_label('only_one_file_can_be_uploaded_at_a_time', 'Only 1 file can be uploaded at a time') }}";
    var label_please_enter_name = "{{ get_label('please_enter_name', 'Please enter name') }}";
    var label_update_the_system = "{{ get_label('update_the_system', 'Update the system') }}";
    var label_sending = "{{ get_label('sending', 'Sending...') }}";
    var label_submit = "{{ get_label('submit', 'Submit') }}";
    var label_allowed_max_upload_size = "{{ get_label('allowed_max_upload_size', 'Allowed max upload size') }}";
    var label_currency_restriction = "{{ get_label('currency_restriction', 'Only digits, commas as thousand separators, and a single decimal point are allowed.') }}";
    var label_currency_restriction_1 = "{{ get_label('currency_restriction_1', 'Only one decimal point is allowed.') }}";
    var label_currency_restriction_2 = "{{ get_label('currency_restriction_2', 'Only digits and a single decimal point are allowed.') }}";
    var label_invoice_id_prefix = "{{ get_label('invoice_id_prefix', 'INVC-') }}";
    var label_please_type_at_least_1_character = "{{ get_label('please_type_at_least_1_character', 'Please type at least 1 character') }}";
    var label_searching = "{{ get_label('searching', 'Searching...') }}";
    var label_no_results_found = "{{ get_label('no_results_found', 'No results found') }}";
    var label_max_files_allowed = "{{ get_label('max_files_allowed', 'Max Files Allowed') }}";
    var label_allowed_file_types = "{{ get_label('allowed_file_types', 'Allowed File Types') }}";
    var label_no_files_chosen = "{{ get_label('no_files_chosen', 'No file(s) chosen.') }}";
    var label_max_files_count_allowed = "{{ get_label('max_files_count_allowed', 'You can only upload :count file(s).') }}";
    var label_file_type_not_allowed = "{{ get_label('file_type_not_allowed', 'File type not allowed') }}";
    var label_mm_export_success = "{{ get_label('mm_export_success', 'Mind map exported successfully!') }}";
    var label_mm_export_failed = "{{ get_label('mm_export_failed', 'Failed to export mind map. Please try again.') }}";
    var label_no_projects_available = "{{ get_label('no_projects_available', 'No Projects Available') }}";
    var label_change_date_not_allowed = "{{ get_label('change_date_not_allowed', 'Change date is not allowed for this.') }}";
    var label_no_data_available = "{{ get_label('no_data_available', 'No Data Available') }}";
    var label_to = "{{ get_label('to', 'To') }}";
    var label_income = "{{ get_label('income', 'Income') }}";
    var label_expense = "{{ get_label('expense', 'Expense') }}";
    var label_amount = "{{ get_label('amount', 'Amount') }}";
    var label_total = "{{ get_label('total', 'Total') }}";
    var label_replies = "{{ get_label('replies', 'Replies') }}";
    var label_jump_to_comment = "{{ get_label('jump_to_comment', 'Jump to Comment') }}";
    var label_edit = "{{ get_label('edit', 'Edit') }}";
    var label_reply = "{{ get_label('reply', 'Reply') }}";
    var label_download = "{{ get_label('download', 'Download') }}";
    var label_preview_not_available = "{{ get_label('preview_not_available', 'Preview not available') }}";
    var label_err_try_again = "{{ get_label('err_try_again', 'An error occurred. Please try again.') }}";
    var label_pinned_successfully = "{{ get_label('pinned_successfully', 'Pinned Successfully.') }}";
    var label_unpinned_successfully = "{{ get_label('unpinned_successfully', 'Unpinned Successfully.') }}";
    var label_click_pin = "{{ get_label('click_pin', 'Click to Pin') }}";
    var label_click_unpin = "{{ get_label('click_unpin', 'Click to Unpin') }}";
    var add_favorite = "{{ get_label('add_favorite', 'Click to mark as favorite') }}";
    var remove_favorite = "{{ get_label('remove_favorite', 'Click to remove from favorite') }}";
    var label_drag_and_drop_file_here = "{{ get_label('drag_and_drop_file_here', 'Drag & Drop File Here') }}";
    var label_no_file_chosen = "{{ get_label('no_file_chosen', 'No file chosen.') }}";
    var label_import_leads = "{{ get_label('import_leads', 'Import Leads') }}";
    var label_enter_project_title_first = "{{ get_label('enter_project_title_first', 'Please enter the project title first.') }}";
    var label_enter_custom_prompt_first = "{{ get_label('enter_custom_prompt_first', 'Please enter a custom prompt first.') }}";

    var label_dashboard = "{{ get_label('dashboard', 'Dashboard') }}";
    var label_productivity_analytics_dashboard = "{{ get_label('productivity_analytics_dashboard', 'Productivity Analytics Dashboard') }}";
    var label_monitor_team_performance = "{{ get_label('monitor_team_performance_and_gain_actionable_insights_in_real_time', 'Monitor team performance and gain actionable insights in real-time.') }}";
    var label_dashboard_description = "{{ get_label('this_dashboard_tracks_active_work_time_manual_entries_breaks_and_productivity_patterns_to_help_optimize_team_performance', 'This dashboard tracks active work time, manual entries, breaks, and productivity patterns to help optimize team performance.') }}";
    var label_select_period = "{{ get_label('select_period', 'Select Period') }}";
    var label_select_period_tooltip = "{{ get_label('choose_a_date_range_to_analyze_productivity_trends_default_shows_last_7_days', 'Choose a date range to analyze productivity trends. Default shows last 7 days.') }}";
    var label_select_date_range = "{{ get_label('select_date_range', 'Select date range') }}";
    var label_quick_select = "{{ get_label('quick_select', 'Quick select') }}";
    var label_today = "{{ get_label('today', 'Today') }}";
    var label_view_today_data = "{{ get_label('view_today_data', 'View today data') }}";
    var label_yesterday = "{{ get_label('yesterday', 'Yesterday') }}";
    var label_view_yesterday_data = "{{ get_label('view_yesterday_data', 'View yesterday data') }}";
    var label_last_7_days = "{{ get_label('last_7_days', 'Last 7 days') }}";
    var label_view_last_7_days_data = "{{ get_label('view_last_7_days_data', 'View last 7 days data') }}";
    var label_last_30_days = "{{ get_label('last_30_days', 'Last 30 days') }}";
    var label_view_last_30_days_data = "{{ get_label('view_last_30_days_data', 'View last 30 days data') }}";
    var label_current_month = "{{ get_label('current_month', 'Current Month') }}";
    var label_view_current_month_data = "{{ get_label('view_current_month_data', 'View current month data') }}";
    var label_select_team_members = "{{ get_label('select_team_members', 'Select Team Member(s)') }}";
    var label_select_team_members_tooltip = "{{ get_label('filter_by_specific_team_members_or_leave_empty_to_view_all_users', 'Filter by specific team members or leave empty to view all users.') }}";
    var label_start_typing_to_search = "{{ get_label('start_typing_to_search_for_team_members', 'Start typing to search for team members') }}";
    var label_loading_team_members = "{{ get_label('loading_team_members', 'Loading team members...') }}";
    var label_all_team_members_selected = "{{ get_label('all_team_members_selected', 'All team members selected') }}";
    var label_select_all = "{{ get_label('select_all', 'Select All') }}";
    var label_clear = "{{ get_label('clear', 'Clear') }}";
    var label_your_productivity_insights = "{{ get_label('your_productivity_insights_at_a_glance', 'Your productivity insights at a glance') }}";
    var label_important_reset_warning = "{{ get_label('important_data_automatically_resets_every_24_hours', 'Important: Data automatically resets every 24 hours!') }}";
    var label_total_projects = "{{ get_label('total_projects', 'Total projects') }}";
    var label_total_tasks = "{{ get_label('total_tasks', 'Total tasks') }}";
    var label_total_users = "{{ get_label('total_users', 'Total users') }}";
    var label_total_clients = "{{ get_label('total_clients', 'Total clients') }}";
    var label_total_meetings = "{{ get_label('total_meetings', 'Total meetings') }}";
    var label_total_todos = "{{ get_label('total_todos', 'Total todos') }}";
    var label_login = "{{ get_label('login', 'Log in') }}";
    var label_register = "{{ get_label('register', 'Register') }}";
    var label_company_title = "{{ $general_settings['company_title'] ?? 'Company' }}";
    var label_no_data_available = "{{ get_label('no_data_available', 'No data available') }}";
    var label_income = "{{ get_label('income', 'Income') }}";
    var label_expenses = "{{ get_label('expenses', 'Expenses') }}";
    var label_total = "{{ get_label('total', 'Total') }}";
    var label_selected = "{{ get_label('selected', 'selected') }}";
    var label_no_todos_found = "{{ get_label('no_todos_found', 'No todos found') }}";
    var label_no_activities_found = "{{ get_label('no_activities_found', 'No activities found') }}";
    var label_drag_to_reorder = "{{ get_label('drag_to_reorder', 'Drag to reorder') }}";
    // Leaves report specific labels
    var label_paid_leaves = "{{ get_label('paid_leaves', 'Paid Leaves') }}";
    var label_unpaid_leaves = "{{ get_label('unpaid_leaves', 'Unpaid Leaves') }}";
    var label_utilization_percent = "{{ get_label('utilization', 'Utilization %') }}";
    var label_users = "{{ get_label('users', 'Users') }}";
    var label_days = "{{ get_label('days', 'Days') }}";
    var label_members_text = "{{ get_label('members', 'Members') }}";
    var label_leaves_taken = "{{ get_label('leaves_taken', 'Leaves Taken') }}";
    var label_months = "{{ get_label('months', 'Months') }}";
    var label_number_of_days = "{{ get_label('number_of_days', 'Number of Days') }}";
    // Paid leave management specific labels
    var label_available = "{{ get_label('available', 'Available:') }}";
    var label_of_text = "{{ get_label('of_text', 'of') }}";
    var label_no_balance = "{{ get_label('no_balance', 'No balance') }}";
    var label_marked_unpaid_if_approved = "{{ get_label('marked_unpaid_if_approved', 'Will be marked as unpaid if approved') }}";
    var label_marked_unpaid = "{{ get_label('marked_unpaid', 'Will be marked as unpaid') }}";
    var label_low_balance = "{{ get_label('low_balance', 'Low balance') }}";
    var label_accrued = "{{ get_label('accrued', 'Accrued') }}";
    var label_earning = "{{ get_label('earning', 'Earning') }}";
    var label_days_per_month = "{{ get_label('days_per_month', 'days/month') }}";
    var label_months_worked = "{{ get_label('months_worked', 'months worked') }}";
    var label_annual = "{{ get_label('annual', 'Annual') }}";
    var label_remaining_leaves = "{{ get_label('remaining_leaves', 'Remaining Leaves') }}";
    var label_remaining_leaves_exhausted_hint = "{{ get_label('remaining_leaves_exhausted_hint', 'No paid days left. Approvals convert to unpaid automatically.') }}";
    var label_remaining_leaves_low_hint = "{{ get_label('remaining_leaves_low_hint', 'Low balance — double-check before approving as paid.') }}";
    var label_remaining_leaves_good_hint = "{{ get_label('remaining_leaves_good_hint', 'Plenty of paid days available.') }}";
    var label_balance_snapshot = "{{ get_label('balance_snapshot', 'Balance snapshot') }}";
    var label_no_recent_leave_activity = "{{ get_label('no_recent_leave_activity', 'No leave decisions recorded yet.') }}";
    var dashboardDataEndpoint = "{{ url('/dashboard/data') }}"; // Hardcoded for now, use route if dynamic
    var invoicesReportEndpoint = "{{ url('/reports/invoices-report-data') }}"; // Hardcoded for now
    var usersListEndpoint = "{{ url('/users/list') }}"; // Hardcoded for now

    // Initialize APP_LABELS for pure JS files
    window.APP_LABELS = window.APP_LABELS || {};
    APP_LABELS['override_required'] = "{{ get_label('override_required', 'Override Required!') }}";
    APP_LABELS['failed_sending_message_try_again'] = "{{ get_label('failed_sending_message_try_again', 'Failed sending the message! Please, try again.') }}";
    APP_LABELS['error_messages_cannot_be_deleted'] = "{{ get_label('error_messages_cannot_be_deleted', 'Error occurred, messages can not be deleted!') }}";
    APP_LABELS['file_type_not_allowed'] = "{{ get_label('file_type_not_allowed', 'File type not allowed') }}";
    APP_LABELS['file_is_too_large'] = "{{ get_label('file_is_too_large', 'File is too large!') }}";
    APP_LABELS['candidate_data_is_missing'] = "{{ get_label('candidate_data_is_missing', 'Candidate data is missing.') }}";
    APP_LABELS['failed_to_load_candidate_profile'] = "{{ get_label('failed_to_load_candidate_profile', 'Failed to load candidate profile.') }}";
    APP_LABELS['no_leave_data_available_yet'] = "{{ get_label('no_leave_data_available_yet', 'No leave data available yet.') }}";
    APP_LABELS['na_text'] = "{{ get_label('na_text', 'N/A') }}";
    APP_LABELS['post_publishing_details'] = "{{ get_label('post_publishing_details', 'Post Publishing Details') }}";
    APP_LABELS['this_field_is_required'] = "{{ get_label('this_field_is_required', 'This field is required.') }}";
    APP_LABELS['error_prefix'] = "{{ get_label('error_prefix', 'Error: ') }}";
    APP_LABELS['edit_field'] = "{{ get_label('edit_field', 'Edit Field') }}";
    APP_LABELS['add_field'] = "{{ get_label('add_field', 'Add Field') }}";
    APP_LABELS['add_candidate_status'] = "{{ get_label('add_candidate_status', 'Add Candidate Status') }}";
</script>
<script>
    function addDebouncedEventListener(selector, event, handler, delay = 300) {
        const debounce = (func, delay) => {
            let timer;
            return function(...args) {
                clearTimeout(timer);
                timer = setTimeout(() => func.apply(this, args), delay);
            };
        };

        $(selector).on(event, debounce(handler, delay));
    }
</script>
